added webvtt exporter (i.e. compiler)
osk/node-webvtt pull request #15
Opened 2018-10-09 18:03 UTC by goatandsheep

exporter is a more descriptive word than compiler, but could be mess up es6 imports

2018-10-19 21:40 UTC, goatandsheep commented
What can I do to speed up time before this can be merged?

2018-10-20 13:14 UTC, osk requested changes
Looks good! Some comment style changes that need to be changed, I've updated my `master` with a new rule so you can rebase and fix.

I wonder if there should be a new integration test suite, i.e. that makes sure something that's parsed and compiled looks like the original again, e.g.:

```javascript
compile(parse(input)).should.equal(input);
```

Also, could you add code examples to `README.md` about how to use this in praxis?

2018-10-20 13:14 UTC, osk commented on lib/compiler.js
> +  }
I want spaces between blocks. eslint rules weren't catching but I just updated `master`, adding the `padding-line-between-statements`

2018-10-20 13:14 UTC, osk commented on lib/compiler.js
> +    ${JSON.stringify(cue)}`);
This looks weird aligned like this, rather keep it all in one line, adding a `/* eslint-disable-line */` to the end

2018-10-20 13:14 UTC, osk commented on lib/compiler.js
> +    typeof cue.identifier !== 'number' &&
I want the expressions aligned, skimming it looks like the expression is not part of the `if`.
Did a quick check of eslint rules but didn't find anything to enforce this

2018-10-20 13:14 UTC, osk commented on lib/compiler.js
> +  output += `${startTimestamp} --> ${endTimestamp} ${cue.styles}\n${cue.text}`;
The space between `${endTimestamp} ${cue.styles}` causes a redundant trailing space if there are no `styles`, it should check if `cue.styles` is set and then adding it + a space

2018-10-20 16:23 UTC, goatandsheep commented on lib/compiler.js
> +  }
I'm so happy you updated eslint. Made the updates really easy

2018-10-20 16:37 UTC, goatandsheep commented
I made the changes

2018-10-20 17:14 UTC, osk approved these changes

2018-10-20 17:14 UTC, merged

2018-10-20 17:14 UTC, osk commented
Nice!

2018-10-20 17:19 UTC, osk commented
v1.2 published with this

2018-10-20 17:39 UTC, goatandsheep commented
I forgot to add the update to the README about usage. I'll add testing config and update README in next PR.